pipeline {
    agent any
    stages {
        stage('---clean---') {
            steps {
                bat "mvn – f(HR_Manager/HrManager/pom.xml) compile"
            }
        }
        stage('--test--') {
            steps {
                bat "mvn test"
            }
        }
        stage('--package--') {
            steps {
                bat "mvn package"
            }
        }
    }
}
